name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
<<<<<<< HEAD
        password: ${{ secrets.GITHUB_TOKEN }} 
        # 添加权限
        scope: "repository:${{ github.repository_owner }}/debianbymy:write,read"
=======
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get current date
      id: date
      run: echo "DATE_TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
>>>>>>> 0b6c8730bf6e6ddb41b7be19fb296c636fbe90c4

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/debianbymy:${{ env.DATE_TAG }}
